version: 'v3'
name: devlopment-environment

services:
  rabbitmq:
    image: rabbitmq:latest
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    ports:
      - 5672:5672
      - 15672:15672
  mongodb:
    image: mongodb/mongodb-community-server:latest
    volumes:
      - ./mongo.conf:/etc/mongo/mongo.conf:ro
    ports:
      - 27017:27017
